### ISSUE TITLE
Cuckoo Configuration

### ISSUE THREAD

**Issue by fareedfauzi** [countercept/snake-scales#8]
Hi Alex.

May I know, if my cuckoo does not use HTTPS, what should I change for the "verify" part? I tried to change to "False" in the conf, and as a result, my sample cannot be submitted by select Cuckoo as the interface's scale. Vice versa, if I'm remain unchanged the default value "True", the sample submit successfully.

![image](https://user-images.githubusercontent.com/56353946/106347966-86a2db80-62fd-11eb-8cdb-7f529d8607c6.png)

**Comment by alexkornitzer** [comment]
So the cuckoo scale is just using requests under to hood, by default requests will set `verify` to `True`:
https://requests.readthedocs.io/en/master/api/#requests.request

In the scale we can see that is just does some lazy construction:
```python
r = requests.post(CUCKOO_API + '/tasks/create/file', files={"file": (document['name'], f)}, verify=VERIFY)
```

So if `CUCKOO_API` is set to `http://hostname:port` it should work without touching `verify`.

Are you saying that the scale is not working at all and always erroring on submission?

**Comment by fareedfauzi** [comment]
Oh. Okay.

The submission is working, but it seems to fail for the Cuckoo retrieving the sample (and analyze) from Snake. The Snake UI keeps showing "Loading..." and the Cuckoo log does not show any indicator of any sample come in. 

![image](https://user-images.githubusercontent.com/56353946/106417778-c6013180-648f-11eb-90dd-cdabeb113928.png)

I thought that the "verify" in my configuration is the problem, that's why I'm asking. I need to figure out other ways, why my Cuckoo can't retrieve the sample.

I also think that the API of my Cuckoo is the actual problem (which maybe misconfiguration or something), but manually submit a sample using the command, based on the Cuckoo [docs](https://cuckoo.readthedocs.io/en/latest/usage/api/#tasks-create-submit) was successfully submitted.
```
curl -H "Authorization: Bearer S4MPL3" http://localhost:8090/tasks/create/submit -F files=@sample.exe
```

Thanks, Alex in advance.

**Comment by alexkornitzer** [comment]
Ahh I think I understand the issue now, do you have authentication sitting on top of your Cuckoo instance?

**Comment by fareedfauzi** [comment]
![image](https://user-images.githubusercontent.com/56353946/106694128-e6a5c480-6612-11eb-88da-82fd51100b03.png)

Based on the above instruction in Cuckoo docs... I never set API an token in my `cuckoo.conf`, so in my case, the authorization of the API might be default implemented.

**Comment by alexkornitzer** [comment]
Right okay lets follow this one through to work out what the real issue is, because I am confused :)

So does the curl work without the authorization header?
- If no, I will need to update the cuckoo scale to support auth headers (probably needs doing anyway)
- If yes, then we have a different issue going on:
  - Can you show me the errors that snake is outputting on submission and viewing?

**Comment by fareedfauzi** [comment]
- It looks like curl work without an authorization header

```
$ curl http://192.168.8.124:8090/tasks/create/submit -F files=@TimeApp.exe
{
  "errors": [],
  "submit_id": 5,
  "task_ids": [
    3
  ]
}
```
![image](https://user-images.githubusercontent.com/56353946/106986188-d2de9780-67a5-11eb-9bb5-73536bd1ba39.png)

- The logs of snake as follow:

Hmm looks like my snake makes a GET request to localhost on port 5000 instead of the IP and port I configured in cuckoo.conf
```
[I 210203 04:01:29 web:2105] 200 GET /scale/cuckoo/interface (127.0.0.1) 1.91ms
[I 210203 04:01:29 web:2105] 200 GET /scale/binwalk/commands (127.0.0.1) 1.84ms
[I 210203 04:01:29 web:2105] 200 GET /store/91fe5ece5b64aff83b9eb0e0ba1b681985d355dcf54864e529570973234e1d1c (127.0.0.1) 6.40ms
[I 210203 04:01:32 web:2105] 200 GET /file/91fe5ece5b64aff83b9eb0e0ba1b681985d355dcf54864e529570973234e1d1c/hex (127.0.0.1) 5.74ms
[E 210203 04:01:32 web:1620] Uncaught exception POST /scale/cuckoo/interface (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:5000', method='POST', uri='/scale/cuckoo/interface', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/dist-packages/tornado-5.0.1-py3.8-linux-x86_64.egg/tornado/web.py", line 1543, in _execute
        result = yield result
      File "/usr/local/lib/python3.8/dist-packages/tornado-5.0.1-py3.8-linux-x86_64.egg/tornado/gen.py", line 1099, in run
        value = future.result()
      File "/usr/local/lib/python3.8/dist-packages/snake-1.0.2-py3.8.egg/snake/routes/scale.py", line 119, in post
        output = await loop.run_in_executor(None, command, data['args'], data['sha256_digest'])
      File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/usr/local/lib/python3.8/dist-packages/snake-1.0.2-py3.8.egg/snake/scale.py", line 737, in wrapper
        output = func(args=args_, file=file_storage, opts=opts, self=self)
      File "/usr/local/lib/python3.8/dist-packages/snake_cuckoo/interface.py", line 28, in info
        j = requests.get(CUCKOO_API + '/files/view/sha256/' + file.sha256_digest, headers=HEADERS, verify=VERIFY).json()    TypeError: unsupported operand type(s) for +: 'int' and 'str'
```

Configuration
```
snake@snake:/var/log/snake$ cat /etc/snake/scales/cuckoo.conf
cuckoo_api: 8090
cuckoo_url: 192.168.8.124

verify: True

snake@snake:/var/log/snake$ cat /usr/local/lib/python3.8/dist-packages/snake_cuckoo/cuckoo.conf
cuckoo_api: 8090
cuckoo_url: 192.168.8.124

verify: True
```

Which part am I wrong Alex?

**Comment by alexkornitzer** [comment]
Right from the logs I can see its due to some un-robust parsing. So if you change your settings to the following you should be good to go:
```
cuckoo_api: 'http://192.168.8.124:8090'
cuckoo_url: 'http://192.168.8.124'
```

**Comment by fareedfauzi** [comment]
Ok issue solved! Thanks a lot.
